name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip autoconf libtool pkg-config wget
          pip install --upgrade pip
          pip install buildozer "cython<3"

      - name: Install Android SDK cmdline tools
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip

          mkdir -p cmdline-tools
          mv cmdline-tools cmdline-tools-temp
          mv cmdline-tools-temp cmdline-tools/latest

      - name: Accept Android licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android packages
        run: |
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;34.0.0" \
          "ndk;25.2.9519653"

      - name: Build APK
        env:
          ANDROIDSDK: $HOME/android-sdk
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
